
FROM node

RUN apt-get update
    

WORKDIR /var/www
RUN mkdir app/
COPY ./server ./app
WORKDIR /var/www/app
RUN chmod +x wait-for-it.sh
RUN  npm init -y && npm install express && npm install mysql2

EXPOSE 3000
